$('.listen').click(function(){
   $('.player').addClass('slide')
  })
$('.player').click(function(){
  $('.player').removeClass('slide')
})
$('.why').click(function(){
   $('.own').addClass('slide')
  })
$('.own').click(function(){
  $('.own').removeClass('slide')
})
$('.products').click(function(){
  $('.shop').addClass('slide')
})
$('.shop').click(function(){
  $('.shop').removeClass('slide')
})